server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: report
          uri: http://localhost:8083
          predicates:
            - Path=/reports/**, 
        - id: customer center
          uri: http://localhost:8084
          predicates:
            - Path=/customerCenters/**, 
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=/undefined/**, 
        - id: phone
          uri: http://localhost:0
          predicates:
            - Path=/phones/**, 
        - id: phone info
          uri: http://localhost:0
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: report
          uri: http://report:8080
          predicates:
            - Path=/reports/**, 
        - id: customer center
          uri: http://customerCenter:8080
          predicates:
            - Path=/customerCenters/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/undefined/**, 
        - id: phone
          uri: http://phone:8080
          predicates:
            - Path=/phones/**, 
        - id: phone info
          uri: http://phoneInfo:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
